### ISSUE TITLE
Investigate weird test failure

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#532]
See branch [TEST_FAILURE_SEED_51958](https://github.com/YaleSTC/vesta/tree/TEST_FAILURE_SEED_51958)

**Comment by orenyk** [comment]
Also seed 14491 on 62ac419

**Comment by orenyk** [comment]
... and the mystery deepens. When I first started investigating the `TEST_FAILURE_SEED_51958` branch was failing repeatedly with seed `51958`, but now it's stopped. The two things I did that could have caused things to work again were:

1. Throw a `binding.pry` in `spec/features/draws/draw_lottery_assignment_spec.rb:20`, run it with some random seed (from Vim), wait about 5-10 minutes (forgot about it), and then simply continue (this unsurprisingly passed).
2. Change the `let` at `spec/features/draws/draw_lottery_assignment_spec.rb:7` to a `let!` and run the suite with seed `51958`.

At this point I give up. I'm leaving this open and we should note any future failures on `spec/features/draws/draw_lottery_assignment_spec.rb:19` or `spec/features/users/intent_spec.rb:23`. The failure message are below:

```
Failures:

  1) Draw lottery assignment can be removed
     Failure/Error: <%= simple_form_for group, url: assign_lottery_draw_group_path(group.draw, group), method: :patch, remote: :true do |f| %>

     ActionView::Template::Error:
       No route matches {:action=>"assign_lottery", :controller=>"groups", :draw_id=>nil, :id=>"1"} missing required keys: [:draw_id]
     # ./app/views/draws/_lottery_form.html.erb:3:in `_app_views_draws__lottery_form_html_erb___1605828521656360024_70326570952600'
     # ./app/views/draws/lottery.html.erb:7:in `block in _app_views_draws_lottery_html_erb___2555115252568850733_70326575671120'
     # ./app/views/draws/lottery.html.erb:5:in `_app_views_draws_lottery_html_erb___2555115252568850733_70326575671120'
     # ------------------
     # --- Caused by: ---
     # ActionController::UrlGenerationError:
     #   No route matches {:action=>"assign_lottery", :controller=>"groups", :draw_id=>nil, :id=>"1"} missing required keys: [:draw_id]
     #   ./app/views/draws/_lottery_form.html.erb:3:in `_app_views_draws__lottery_form_html_erb___1605828521656360024_70326570952600'

  2) Housing Intent admin can lock intent changes on a per draw basis
     Failure/Error: @draw = Draw.includes(:groups, :suites).find(params[:id])

     ActiveRecord::RecordNotFound:
       Couldn't find Draw with 'id'=1
     # ./app/controllers/draws_controller.rb:214:in `set_draw'
     # ------------------
     # --- Caused by: ---
     # Capybara::ElementNotFound:
     #   Unable to find link or button "Lock Intents"
     #   ./spec/features/users/intent_spec.rb:33:in `lock_intent'

Finished in 1 minute 27.63 seconds (files took 4.24 seconds to load)
1065 examples, 2 failures, 24 pending

Failed examples:

rspec ./spec/features/draws/draw_lottery_assignment_spec.rb:19 # Draw lottery assignment can be removed
rspec ./spec/features/users/intent_spec.rb:23 # Housing Intent admin can lock intent changes on a per draw basis

Randomized with seed 51958
```

**Comment by orenyk** [comment]
[Here](https://travis-ci.org/YaleSTC/vesta/builds/222204967)'s another example (seed 4060, commit irrelevant since it's a PR build).

**Comment by orenyk** [comment]
3a9b682 w/ seed 51098 ([build](https://travis-ci.org/YaleSTC/vesta/builds/223693984))
